"""add all tables

Revision ID: d2369a85ca80
Revises: d15f3da38dbd
Create Date: 2025-12-24 16:15:37.433449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2369a85ca80'
down_revision: Union[str, Sequence[str], None] = 'd15f3da38dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generationhistorys',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('gen_successful', sa.Boolean(), nullable=False),
    sa.Column('gen_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generationhistorys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generationhistorys'))
    )
    op.create_table('payments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('rub_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('canceled', 'pending', 'completed', 'succeeded', name='payment_status_enum'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_payments_payment_id'))
    )
    op.create_table('referralbonuss',
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_type', sa.Enum('deposit', 'generation', name='bonus_type_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('deposit_rub_amount', sa.Integer(), nullable=False),
    sa.Column('deposit_token_amount', sa.Integer(), nullable=False),
    sa.Column('pay_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pay_id'], ['payments.id'], name=op.f('fk_referralbonuss_pay_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ref_id'], ['users.id'], name=op.f('fk_referralbonuss_ref_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referralbonuss'))
    )
    op.drop_constraint(op.f('users_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_user_id'), 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_id'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_user_id_key'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('referralbonuss')
    op.drop_table('payments')
    op.drop_table('generationhistorys')
    # ### end Alembic commands ###
