"""fixed tablenames

Revision ID: 8ecde74ea4d0
Revises: d2369a85ca80
Create Date: 2025-12-26 21:42:06.621465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "8ecde74ea4d0"
down_revision: Union[str, Sequence[str], None] = "d2369a85ca80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # safely create the enum if it doesn't exist
    bonus_enum = postgresql.ENUM(
        "deposit", "generation", name="bonus_type_enum", create_type=True
    )
    bonus_enum.create(bind=op.get_bind(), checkfirst=True)

    op.create_table(
        "generation_history",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("request", sa.Text(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("gen_successful", sa.Boolean(), nullable=False),
        sa.Column("gen_type", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generation_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_history")),
    )
    op.create_table(
        "user_sources",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("source_value", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sources_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sources")),
    )

    bonus_enum = postgresql.ENUM(
        "deposit", "generation", name="bonus_type_enum", create_type=False
    )
    op.create_table(
        "referral_bonuses",
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bonus_type", bonus_enum, nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("deposit_rub_amount", sa.Integer(), nullable=False),
        sa.Column("deposit_token_amount", sa.Integer(), nullable=False),
        sa.Column("pay_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pay_id"],
            ["payments.id"],
            name=op.f("fk_referral_bonuses_pay_id_payments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ref_id"],
            ["users.id"],
            name=op.f("fk_referral_bonuses_ref_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_bonuses")),
    )
    op.drop_table("generationhistorys")
    op.drop_table("usersources")
    op.drop_table("referralbonuss")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referralbonuss",
        sa.Column("ref_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("referred_user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("referrer_user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "bonus_type",
            postgresql.ENUM("deposit", "generation", name="bonus_type_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "deposit_rub_amount", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "deposit_token_amount", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("pay_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pay_id"],
            ["payments.id"],
            name=op.f("fk_referralbonuss_pay_id_payments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ref_id"],
            ["users.id"],
            name=op.f("fk_referralbonuss_ref_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referralbonuss")),
    )
    op.create_table(
        "usersources",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("source_value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("usersources_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("usersources_pkey")),
    )
    op.create_table(
        "generationhistorys",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("request", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("cost", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gen_successful", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("gen_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generationhistorys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generationhistorys")),
    )
    op.drop_table("referral_bonuses")
    op.drop_table("user_sources")
    op.drop_table("generation_history")
    # ### end Alembic commands ###
