"""uq_user_bonus

Revision ID: 702eca23867a
Revises: 81713241669c
Create Date: 2026-01-27 02:06:20.983125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702eca23867a'
down_revision: Union[str, Sequence[str], None] = '81713241669c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_bonus', 'user_bonuses', ['user_id', 'bonus_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_bonus', 'user_bonuses', type_='unique')
    # ### end Alembic commands ###
