"""added latest_daily_card to user

Revision ID: 8cda14a63c92
Revises: 1406069786ec
Create Date: 2026-01-06 00:11:14.009970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cda14a63c92'
down_revision: Union[str, Sequence[str], None] = '1406069786ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latest_daily_card', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'latest_daily_card')
    # ### end Alembic commands ###
