"""gen enum

Revision ID: 95663d03d16a
Revises: 7e5a08b08723
Create Date: 2026-01-24 12:56:48.819155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95663d03d16a"
down_revision: Union[str, Sequence[str], None] = "7e5a08b08723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_history",
        sa.Column(
            "gen_status",
            sa.Enum(
                "success",
                "error",
                "not_enough_balance",
                "already_generated_today",
                name="gen_status_enum",
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "generation_history",
        "request",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
        postgresql_using="request::text",
    )
    op.drop_column("generation_history", "gen_successful")
    op.drop_column("generation_history", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_history",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "generation_history",
        sa.Column("gen_successful", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "generation_history",
        "request",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("generation_history", "gen_status")
    # ### end Alembic commands ###
