"""new table for bonuses

Revision ID: 7e5a08b08723
Revises: 3bce99b99cd2
Create Date: 2026-01-17 15:44:55.672393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5a08b08723'
down_revision: Union[str, Sequence[str], None] = '3bce99b99cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bonuses',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('deposited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_bonuses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_bonuses'))
    )
    op.alter_column('users', 'segment',
               existing_type=postgresql.ENUM('lead', 'qual', 'client', 'banned', name='segment_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'segment',
               existing_type=postgresql.ENUM('lead', 'qual', 'client', 'banned', name='segment_enum'),
               nullable=True)
    op.drop_table('user_bonuses')
    # ### end Alembic commands ###
